#!/bin/bash

# Sweeping different models over masking strategies

# Basic Latent MIM
python scripts/v0_sweep/latent_mim.py launch v0_base_latent_mim_random_fsdp ai2/jupiter-cirrascale-2 --model.decoder_config.depth=4 --common.launch.num_gpus=8 --train_module.masking_config.strategy_config.type=random  --model.reconstructor_config=null --train_module.mae_loss_config=null
python scripts/v0_sweep/latent_mim.py launch v0_base_latent_mim_space_time_fsdp ai2/jupiter-cirrascale-2 --model.decoder_config.depth=4 --common.launch.num_gpus=8 --train_module.masking_config.strategy_config.type=space_time --model.reconstructor_config=null --train_module.mae_loss_config=null
python scripts/v0_sweep/latent_mim.py launch v0_base_latent_mim_cross_space_fsdp ai2/jupiter-cirrascale-2 --model.decoder_config.depth=4 --common.launch.num_gpus=8 --train_module.masking_config.strategy_config.type=modality_cross_space --model.reconstructor_config=null --train_module.mae_loss_config=null
python scripts/v0_sweep/latent_mim.py launch v0_base_latent_mim_cross_space_time_fsdp ai2/jupiter-cirrascale-2 --model.decoder_config.depth=4 --common.launch.num_gpus=8 --train_module.masking_config.strategy_config.type=modality_cross_space_time --model.reconstructor_config=null --train_module.mae_loss_config=null

# Latent MIM + Contrastive
python scripts/v0_sweep/contrastive_latent_mim.py launch v0_base_latent_mim_contrastive_random_fsdp ai2/jupiter-cirrascale-2 --model.decoder_config.depth=4 --common.launch.num_gpus=8 --train_module.masking_config.strategy_config.type=random  --model.reconstructor_config=null --train_module.mae_loss_config=null
python scripts/v0_sweep/contrastive_latent_mim.py launch v0_base_latent_mim_contrastive_space_time_fsdp ai2/jupiter-cirrascale-2 --model.decoder_config.depth=4 --common.launch.num_gpus=8 --train_module.masking_config.strategy_config.type=space_time --model.reconstructor_config=null --train_module.mae_loss_config=null
python scripts/v0_sweep/contrastive_latent_mim.py launch v0_base_latent_mim_contrastive_cross_space_fsdp ai2/jupiter-cirrascale-2 --model.decoder_config.depth=4 --common.launch.num_gpus=8 --train_module.masking_config.strategy_config.type=modality_cross_space --model.reconstructor_config=null --train_module.mae_loss_config=null
python scripts/v0_sweep/contrastive_latent_mim.py launch v0_base_latent_mim_contrastive_cross_space_time_fsdp ai2/jupiter-cirrascale-2 --model.decoder_config.depth=4 --common.launch.num_gpus=8 --train_module.masking_config.strategy_config.type=modality_cross_space_time --model.reconstructor_config=null --train_module.mae_loss_config=null

# Basic Galileo
python scripts/v0_sweep/galileo.py launch v0_base_galileo_random_x_random_fsdp ai2/jupiter-cirrascale-2 --model.decoder_config.depth=4 --common.launch.num_gpus=8 --train_module.masking_config_a.strategy_config.type=random --model.reconstructor_config=null --train_module.mae_loss_config=null --train_module.contrastive_config=null
python scripts/v0_sweep/galileo.py launch v0_base_galileo_random_x_space_time_fsdp ai2/jupiter-cirrascale-2 --model.decoder_config.depth=4 --common.launch.num_gpus=8 --train_module.masking_config_a.strategy_config.type=space_time --model.reconstructor_config=null --train_module.mae_loss_config=null --train_module.contrastive_config=null
python scripts/v0_sweep/galileo.py launch v0_base_galileo_random_x_cross_space_fsdp ai2/jupiter-cirrascale-2 --model.decoder_config.depth=4 --common.launch.num_gpus=8 --train_module.masking_config_a.strategy_config.type=modality_cross_space --model.reconstructor_config=null --train_module.mae_loss_config=null --train_module.contrastive_config=null
python scripts/v0_sweep/galileo.py launch v0_base_galileo_random_x_cross_space_time_fsdp ai2/jupiter-cirrascale-2 --model.decoder_config.depth=4 --common.launch.num_gpus=8 --train_module.masking_config_a.strategy_config.type=modality_cross_space_time --model.reconstructor_config=null --train_module.mae_loss_config=null --train_module.contrastive_config=null

# Contrastive Galileo
python scripts/v0_sweep/galileo.py launch v0_base_galileo_contrastive_random_x_random_fsdp ai2/jupiter-cirrascale-2 --model.decoder_config.depth=4 --common.launch.num_gpus=8 --train_module.masking_config_a.strategy_config.type=random  --model.reconstructor_config=null --train_module.mae_loss_config=null
python scripts/v0_sweep/galileo.py launch v0_base_galileo_contrastive_random_x_space_time_fsdp ai2/jupiter-cirrascale-2 --model.decoder_config.depth=4 --common.launch.num_gpus=8 --train_module.masking_config_a.strategy_config.type=space_time --model.reconstructor_config=null --train_module.mae_loss_config=null
python scripts/v0_sweep/galileo.py launch v0_base_galileo_contrastive_random_x_cross_space_fsdp ai2/jupiter-cirrascale-2 --model.decoder_config.depth=4 --common.launch.num_gpus=8 --train_module.masking_config_a.strategy_config.type=modality_cross_space --model.reconstructor_config=null --train_module.mae_loss_config=null
python scripts/v0_sweep/galileo.py launch v0_base_galileo_contrastive_random_x_cross_space_time_fsdp ai2/jupiter-cirrascale-2 --model.decoder_config.depth=4 --common.launch.num_gpus=8 --train_module.masking_config_a.strategy_config.type=modality_cross_space_time --model.reconstructor_config=null --train_module.mae_loss_config=null

# SpT Latent MIM
python scripts/v0_sweep/latent_mim_st.py launch v0_base_SpT_latentmim_random_fsdp ai2/jupiter-cirrascale-2 --train_module.masking_config.strategy_config.type=random --common.launch.num_gpus=8 --model.reconstructor_config=null --train_module.mae_loss_config=null --data_loader.token_budget=6000 --train_module.rank_microbatch_size=16
python scripts/v0_sweep/latent_mim_st.py launch v0_base_SpT_latentmim_space_time_fsdp ai2/jupiter-cirrascale-2 --train_module.masking_config.strategy_config.type=space_time --common.launch.num_gpus=8  --model.reconstructor_config=null --train_module.mae_loss_config=null --data_loader.token_budget=6000 --train_module.rank_microbatch_size=16
python scripts/v0_sweep/latent_mim_st.py launch v0_base_SpT_latentmim_cross_space_fsdp ai2/jupiter-cirrascale-2 --train_module.masking_config.strategy_config.type=modality_cross_space --common.launch.num_gpus=8  --model.reconstructor_config=null --train_module.mae_loss_config=null --data_loader.token_budget=6000 --train_module.rank_microbatch_size=16
python scripts/v0_sweep/latent_mim_st.py launch v0_base_SpT_latentmim_cross_space_time_fsdp ai2/jupiter-cirrascale-2 --train_module.masking_config.strategy_config.type=modality_cross_space_time --common.launch.num_gpus=8  --model.reconstructor_config=null --train_module.mae_loss_config=null --data_loader.token_budget=6000 --train_module.rank_microbatch_size=16

# SpT Contrastive Latent MIM
python scripts/v0_sweep/contrastive_latent_mim_st.py launch v0_base_SpT_latentmim_contrastive_random_fsdp ai2/jupiter-cirrascale-2 --train_module.masking_config.strategy_config.type=random --common.launch.num_gpus=8 --model.reconstructor_config=null --data_loader.token_budget=3000 --train_module.rank_microbatch_size=16 --train_module.mae_loss_config=null
python scripts/v0_sweep/contrastive_latent_mim_st.py launch v0_base_SpT_latentmim_contrastive_space_time_fsdp ai2/jupiter-cirrascale-2 --train_module.masking_config.strategy_config.type=space_time --common.launch.num_gpus=8  --model.reconstructor_config=null --data_loader.token_budget=3000 --train_module.rank_microbatch_size=16 --train_module.mae_loss_config=null
python scripts/v0_sweep/contrastive_latent_mim_st.py launch v0_base_SpT_latentmim_contrastive_cross_space_fsdp ai2/jupiter-cirrascale-2 --train_module.masking_config.strategy_config.type=modality_cross_space --common.launch.num_gpus=8  --model.reconstructor_config=null --data_loader.token_budget=3000 --train_module.rank_microbatch_size=16 --train_module.mae_loss_config=null
python scripts/v0_sweep/contrastive_latent_mim_st.py launch v0_base_SpT_latentmim_contrastive_cross_space_time_fsdp ai2/jupiter-cirrascale-2 --train_module.masking_config.strategy_config.type=modality_cross_space_time --common.launch.num_gpus=8  --model.reconstructor_config=null --data_loader.token_budget=3000 --train_module.rank_microbatch_size=16 --train_module.mae_loss_config=null

# SpT Galileo
python scripts/v0_sweep/galileo_st.py launch v0_base_SpT_galileo_space_time_fsdp ai2/jupiter-cirrascale-2  --model.decoder_config.depth=8 --train_module.masking_config_a.strategy_config.type=space_time --common.launch.num_gpus=8 --train_module.contrastive_config=null --model.reconstructor_config=null --train_module.mae_loss_config=null --data_loader.token_budget=1500
python scripts/v0_sweep/galileo_st.py launch v0_base_SpT_galileo_cross_space_fsdp ai2/jupiter-cirrascale-2  --model.decoder_config.depth=8 --train_module.masking_config_a.strategy_config.type=modality_cross_space --common.launch.num_gpus=8 --train_module.contrastive_config=null --model.reconstructor_config=null --train_module.mae_loss_config=null --data_loader.token_budget=1500
python scripts/v0_sweep/galileo_st.py launch v0_base_SpT_galileo_cross_space_time_fsdp ai2/jupiter-cirrascale-2  --model.decoder_config.depth=8 --train_module.masking_config_a.strategy_config.type=modality_cross_space_time --common.launch.num_gpus=8 --train_module.contrastive_config=null --model.reconstructor_config=null --train_module.mae_loss_config=null --data_loader.token_budget=1500

# Some MAE Expts
python scripts/v0_sweep/latent_mim_st.py launch v0_base_SpT_latentmim_mae_random_fsdp ai2/jupiter-cirrascale-2 --train_module.masking_config.strategy_config.type=random --common.launch.num_gpus=8 --data_loader.token_budget=3000 --train_module.rank_microbatch_size=16
python scripts/v0_sweep/contrastive_latent_mim_st.py launch v0_base_SpT_latentmim_contrastive_mae_random_fsdp ai2/jupiter-cirrascale-2 --train_module.masking_config.strategy_config.type=random --common.launch.num_gpus=8 --data_loader.token_budget=2000 --train_module.rank_microbatch_size=16
python scripts/v0_sweep/latent_mim.py launch v0_base_latent_mim_mae_random_fsdp ai2/jupiter-cirrascale-2 --model.decoder_config.depth=4 --common.launch.num_gpus=8 --train_module.masking_config.strategy_config.type=random
python scripts/v0_sweep/galileo.py launch v0_base_galileo_contrastive_mae_random_x_random_fsdp ai2/jupiter-cirrascale-2 --model.decoder_config.depth=4 --common.launch.num_gpus=8 --train_module.masking_config_a.strategy_config.type=random
